import Header from '@/components/Header';
import '@/styles/globals.css';

export const metadata = {
  title: 'Product Catalog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
